[package]
name = "garble"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
bytecheck = "0.8.1"
rand = "0.9.1"
rand_chacha = "0.9.0"
rkyv = "0.8.10"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11.17"
sha2 = "0.10.8"
