[package]
name = "validityproof"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Zero-knowledge proof generator for verifiable garbled circuits using RISC Zero"
license.workspace = true
repository.workspace = true
keywords = ["zero-knowledge", "risc0", "garbled-circuits", "zk-proof"]
categories = ["cryptography", "command-line-utilities"]
readme = "../../README.md"

[dependencies]
bytecheck.workspace = true
bytemuck.workspace = true
garble.workspace = true
garbling-methods.workspace = true
risc0-zkvm.workspace = true
rkyv.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
validityproof-core.workspace = true

[features]
cuda = ["risc0-zkvm/cuda"]
default = []
prove = ["risc0-zkvm/prove"]
