[package]
name = "validityproof"
version = "0.1.0"
edition = "2021"

[dependencies]
bytecheck.workspace = true
bytemuck.workspace = true
garble.workspace = true
garbling-methods.workspace = true
risc0-zkvm.workspace = true
rkyv.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
validityproof-core.workspace = true

[features]
cuda = ["risc0-zkvm/cuda"]
default = []
prove = ["risc0-zkvm/prove"]
