[package]
name = "freexorgarble"
version = "0.12.0"
edition = "2021"

[dependencies]
garble.workspace = true
risc0-zkvm = { workspace = true, default-features = false, features = [
  "std",
  "heap-embedded-alloc",
] }
rkyv.workspace = true
validityproof-core.workspace = true
