[package]
name = "freexorgarble"
version = "0.12.0"
edition = "2021"

[dependencies]
risc0-zkvm = { git = "https://github.com/risc0/risc0.git", tag = "v2.0.2", default-features = false, features = [
  "std",
  "heap-embedded-alloc",
] }
garble.workspace = true
rkyv.workspace = true
validityproof-core.workspace = true
