[package]
name = "garbling-methods"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "RISC Zero guest methods for garbled circuit validity proofs"
license.workspace = true
repository.workspace = true
keywords = ["risc0", "guest-methods", "zero-knowledge", "garbled-circuits"]
categories = ["cryptography"]
readme = "../../../README.md"

[build-dependencies]
risc0-build.workspace = true

[package.metadata.risc0]
methods = ["guest"]
