name: Docs

on:
  pull_request:
  merge_group:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

permissions: {}

jobs:
  docs:
    name: Generate docs
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@fcf085fcb4b4b8f63f96906cd713eb52181b5ea4 # stable

      - name: Install rzup and risczero
        run: |
          set -e
          curl -L https://risczero.com/install | bash
          export PATH="$HOME/.risc0/bin:$PATH"
          rzup install cargo-risczero 2.0.2
          rzup install rust 1.85.0 # set this to the desired risc0 rust toolchain.

      - name: Rust cache
        uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2
        with:
          cache-on-failure: true

      - name: Check docs leaving the dependencies out
        env:
          RUSTDOCFLAGS: -A rustdoc::private-doc-tests -D warnings
        run: cargo doc --no-deps
