# Check pull requests for typos.
#
# Configuration: .github/_typos.toml
#
# Info:          https://github.com/marketplace/actions/typos-action
# Local install: brew install typos-cli
# Local install: conda install typos
# Local run:     typos -c .github/_typos.toml

name: Spell Check

on:
  pull_request:
  merge_group:
  push:
    branches: [main]

permissions: {}

jobs:
  run:
    name: Spell Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: Use custom config file
        uses: crate-ci/typos@392b78fe18a52790c53f42456e46124f77346842 #v1.34.0
        with:
          config: .github/_typos.toml
          write_changes: false